name:                ghoauth
version:             0.1.1
homepage:            https://github.com/matsubara0507/ghoauth#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2021 MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/ghoauth#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- extensible >= 0.6
- req >= 2.0.0

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - microlens
  - simple-api
  - text
  - unordered-containers

executables:
  ghoauth:
    main: Main.hs
    source-dirs: app
    dependencies:
    - dotenv
    - fallible
    - ghoauth
    - githash
    - mix
    - open-browser
    - rio >= 0.1.1.0

tests:
  ghoauth-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aeson
    - ghoauth
    - req
    - servant-server
    - simple-api
    - tasty
    - tasty-hspec
    - warp
