resolver: lts-17.15
packages:
- '.'
extra-deps:
- extensible-0.8.2
- fallible-0.1.0
- incremental-0.3.1
- membership-0
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
- github: matsubara0507/extensible-ext
  commit: a9c5e50696f8205d17628625f5b724ef92557aeb
  subdirs:
  - simple-api

docker:
  repo: ghcr.io/matsubara0507/stack-build:18.04
  enable: false
